name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build & test
        run: ./gradlew assemble test jacocoTestReport
      - name: archive test results
        if: failure()
        run: (cd vdm/build/reports/tests/test; zip -r -X ../../../../../test-result.zip .)
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: test-result.zip
      - name: archive test coverage
        run: (cd vdm/build/reports/jacoco/test/html; zip -r -X ../../../../../test-coverage.zip .)
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: test-coverage
          path: test-coverage.zip
      - name: codecov unit tests
        run: bash <(curl -s https://codecov.io/bash) -f ./vdm/build/reports/jacoco/test/jacocoTestReport.xml -F unit
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
